# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        compound: 5
        affinity: 5
        ligand: 5
        protein: 5
        drug: 5
        drug discovery: 10
        molecule: 5

# 通知の閾値
score_threshold: 0
